### ISSUE TITLE
Not able to add more than one CDA query

### ISSUE THREAD

**Issue by JBComputech** [SPECUSA/SelfServiceBI#11]
Hi,

 I am not able to add  than one CDA query, it allows to add many saiku data sources but after adding one cda query, the plus icon disappears and no option to add the new cda query.

I tried debug the same and done add a condition in the pinboardEdit.html file as follows:

 <div ng-show="isDbListNull||dboption=='saiku'||dboption=='cda'"> and then it works..

So just wanted to check, is this the right approach to fix this issue or there is other options to fix this.

Please help.

This issue exist in both   SSBI Version.-- 2.0.1_p07_1_community and  SSBI Version.-- 2.0.2_p07_1_community versions.

**Comment by SPECUSA** [comment]
Hi,

 

In single CDA file , Please define the multiple queries. In visualization , Please specify the appropriate ID of CDA query. 

 

Regards, Pranav

**Comment by JBComputech** [comment]
Thanks Pranav,

I will try that and update you.
