### ISSUE TITLE
Save As Option is not working

### ISSUE THREAD

**Issue by JBComputech** [SPECUSA/SelfServiceBI#13]
Hi,
I have created one pin board and tried to do save as of the same  but the save as button is not working.
I have tried this with the latest release of SSBI.

Kindly help on this...

**Comment by JBComputech** [comment]
Hi,
Any update on this..

**Comment by SPECUSA** [comment]
Hi,

We are checking it.

Next version will be released soon

**Comment by SPECUSA** [comment]
Solved in new version 2.1.1
