### ISSUE TITLE
 User doesn't have permission to access the data

### ISSUE THREAD

**Issue by EmannuelRoque** [SPECUSA/SelfServiceBI#7]
Hi. Congratulations for the great tool! 

I'm getting the message:
"User doesn't have permission to access the data" when I try to open a saved pin with a saiku file as datasource.

Its working when I'm creating it.

Thanks!
Pentaho 7.1

**Comment by SPECUSA** [comment]
Hi @EmannuelRoque 

Please download new version from marketplace with fixed issue

Cheers!!
