### ISSUE TITLE
Add a Gauge

### ISSUE THREAD

**Issue by ahcneto** [SPECUSA/SelfServiceBI#8]
hi ! the version 2.0.0 is amazing ! congrats !!!

It's possible add a custom fusionchart code ? for example, add a gauge ?  or using a SolidGauge on HighChart component ?

I need build a dashboard with gauge, and i would like make it on SelfService BI.

Kind regards,

Aristeu

**Comment by SPECUSA** [comment]
Hi @ahcneto 

We have added Gauge chart for Highchart library in new version 2.0.2.

Please update to new version from marketplace
