### ISSUE TITLE
Date should be in format YYYY-MM-DD

### ISSUE THREAD

**Issue by sagarshewale** [SPECUSA/SelfServiceBI#9]
Hi ,

when i am trying to create filter of type DatePicker it is always saying "**Date should be in format YYYY-MM-DD**".

Even if the default value i have entered is in Perfect Format as Mentioned (YYYY-MM-DD).

anybody resolved this?

**Comment by SPECUSA** [comment]
Hi @sagarshewale 

Please update to new version of SelfServiceBI, v2.0.2
